plugins {
    id 'java-library'
}

dependencies {
    api project(':core')
    api project(':registry')
    api project(':config')
    api project(':mq')
    api project(':runtime')
    api project(':reliability')
    api libs.springboot.starter
    api libs.springboot.config.processor
    // For HealthIndicator compile-time visibility (do not force runtime)
    compileOnly libs.springboot.actuator
    compileOnly libs.springboot.starter.actuator
    api libs.micrometer.core

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    annotationProcessor libs.springboot.config.processor

    testImplementation libs.springboot.starter.test
    testImplementation libs.springboot.starter.web
    testImplementation libs.springboot.starter.actuator
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
}
