plugins {
    id 'java-library'
}

dependencies {
    api project(':core')

    // Redis client
    implementation libs.redisson

    // Logging
    implementation libs.slf4j.api

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
}
