plugins {
    id 'java-library'
}

dependencies {
    api libs.redisson
    api libs.jackson.databind
    api libs.slf4j.api

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    testImplementation libs.junit.jupiter
    testImplementation libs.junit.api
    testRuntimeOnly libs.junit.engine
    testRuntimeOnly libs.junit.launcher
    testImplementation libs.mockito.core
    testImplementation libs.slf4j.simple
}