plugins {
    id 'java-library'
}

dependencies {
    api project(':core')

    // Redisson for distributed deduplication
    implementation libs.redisson

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
}
