plugins {
    id 'java-library'
}

dependencies {
    api project(':core')
    implementation project(':runtime')

    // Redis client for Redis KTable
    implementation libs.redisson

    // Jackson for JSON serialization
    implementation libs.jackson.databind

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
}
