name: Full Test Suite

on:
  schedule:
    - cron: '0 3 * * 0'  # 每周日凌晨 3 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  full-test:
    runs-on: self-hosted
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Java version
      run: |
        java -version
        echo "JAVA_HOME=$JAVA_HOME"

    - name: Grant execute permission
      run: chmod +x gradlew deploy/verify-services.sh

    - name: Clean previous build
      run: ./gradlew clean --console=plain

    - name: Verify system services
      run: |
        echo "=== System Service Status ==="
        ./deploy/verify-services.sh

    - name: Ensure all services are running
      run: |
        echo "=== Starting All Services ==="
        sudo systemctl start redis-server mysql postgresql elasticsearch || true
        sleep 45

    - name: Wait for all services
      run: |
        echo "Waiting for services to be healthy..."
        for i in {1..30}; do
          ALL_READY=true

          # Check Redis
          if ! redis-cli ping > /dev/null 2>&1; then
            ALL_READY=false
            echo "Redis not ready yet..."
          fi

          # Check MySQL
          if ! mysql -h 127.0.0.1 -u test_user -ptest_password test_db -e "SELECT 1" > /dev/null 2>&1; then
            ALL_READY=false
            echo "MySQL not ready yet..."
          fi

          # Check PostgreSQL
          if ! PGPASSWORD=test_password psql -h 127.0.0.1 -U test_user -d test_db -c "SELECT 1" > /dev/null 2>&1; then
            ALL_READY=false
            echo "PostgreSQL not ready yet..."
          fi

          if [ "$ALL_READY" = true ]; then
            echo "All services are ready!"
            break
          else
            echo "Attempt $i/30: Waiting for services..."
            sleep 10
          fi
        done

        echo "=== Final Service Status ==="
        sudo systemctl status redis-server --no-pager || true
        sudo systemctl status mysql --no-pager || true
        sudo systemctl status postgresql --no-pager || true

    - name: Run all tests
      run: ./gradlew clean build test integrationTest --console=plain --stacktrace

    - name: Generate test report
      if: always()
      run: |
        echo "=== Test Summary ==="
        find . -name "TEST-*.xml" -type f | wc -l | xargs echo "Total test files:"

    - name: Collect all logs
      if: always()
      run: |
        mkdir -p build/full-test-logs

        # Gradle reports
        cp -r build/reports build/full-test-logs/ 2>/dev/null || true

        # System service logs
        sudo journalctl -u redis-server -n 100 > build/full-test-logs/redis.log 2>&1 || true
        sudo journalctl -u mysql -n 100 > build/full-test-logs/mysql.log 2>&1 || true
        sudo journalctl -u postgresql -n 100 > build/full-test-logs/postgresql.log 2>&1 || true
        sudo journalctl -u elasticsearch -n 100 > build/full-test-logs/elasticsearch.log 2>&1 || true

    - name: Upload full test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: full-test-results
        path: |
          **/build/test-results/
          **/build/reports/
          build/full-test-logs/
        retention-days: 14

    - name: Cleanup
      if: always()
      run: |
        echo "Tests completed, services will continue running for next workflow"
