name: Publish to Maven Central

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 30
    concurrency:
      group: publish-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Java version
      run: |
        java -version
        echo "JAVA_HOME=$JAVA_HOME"

    - name: Assert Java 17
      run: |
        MAJOR=$(java -version 2>&1 | awk -F[".] '/version/ {print $2}')
        echo "Detected Java major: $MAJOR"
        if [ "$MAJOR" != "17" ]; then
          echo "❌ Expected Java 17 but found: $(java -version 2>&1 | head -n 1)"
          exit 1
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix if present
        elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ inputs.version }}"
        else
          VERSION="$(grep '^version' build.gradle | sed "s/.*'\(.*\)'.*/\1/")"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Publishing version: ${VERSION}"

    - name: Update version in build.gradle
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        sed -i "s/version = '.*'/version = '${VERSION}'/" build.gradle
        echo "Updated version to: ${VERSION}"
        grep "version = " build.gradle

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Import GPG private key (for signing)
      if: env.GPG_PRIVATE_KEY != ''
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "Importing GPG key..."
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        gpg --list-secret-keys --keyid-format=long || true

    - name: Prepare signing configuration
      run: |
        mkdir -p ~/.gradle
        cat > ~/.gradle/gradle.properties << 'EOF'
        # Signing via environment variables; gradle build picks up GPG_* if provided
        # Provide these secrets in repo settings when publishing
        # GPG_KEY_ID / GPG_PASSWORD / GPG_SECRET_KEY (optional if gpg agent is used)
        EOF
        echo "✓ signing configuration ready (env-driven)"

    - name: Build and test
      run: ./gradlew clean build -x integrationTest --console=plain

    - name: Publish to Central Portal
      env:
        CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
        CENTRAL_PORTAL_TOKEN: ${{ secrets.CENTRAL_PORTAL_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      run: |
        echo "Publishing to Central Portal..."
        ./gradlew publish --console=plain --stacktrace

    - name: Create release notes
      if: github.event_name == 'release'
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        echo "# Release v${VERSION}" > release-notes.md
        echo "" >> release-notes.md
        echo "## Published Modules" >> release-notes.md
        echo "" >> release-notes.md
        ./gradlew projects | grep -E "^(Project|---)" | grep -v "^---" | grep -v "^Project ':'" | sed 's/Project/- /' >> release-notes.md || echo "- All modules" >> release-notes.md
        echo "" >> release-notes.md
        echo "## Maven Coordinates" >> release-notes.md
        echo "" >> release-notes.md
        echo '```xml' >> release-notes.md
        echo '<dependency>' >> release-notes.md
        echo '    <groupId>io.github.cuihairu.redis-streaming</groupId>' >> release-notes.md
        echo '    <artifactId>MODULE_NAME</artifactId>' >> release-notes.md
        echo "    <version>${VERSION}</version>" >> release-notes.md
        echo '</dependency>' >> release-notes.md
        echo '```' >> release-notes.md
        echo "" >> release-notes.md
        echo "## Gradle" >> release-notes.md
        echo "" >> release-notes.md
        echo '```gradle' >> release-notes.md
        echo "implementation 'io.github.cuihairu.redis-streaming:MODULE_NAME:${VERSION}'" >> release-notes.md
        echo '```' >> release-notes.md

    - name: Upload release notes
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: release-notes.md
        retention-days: 90

    - name: Comment on release
      if: github.event_name == 'release' && success()
      uses: actions/github-script@v7
      with:
        script: |
          const version = '${{ steps.version.outputs.VERSION }}';
          const body = `✅ Successfully published version **${version}** to Maven Central!

          The artifacts will be available on Maven Central within a few hours:
          https://search.maven.org/search?q=g:io.github.cuihairu.redis-streaming

          ## Usage

          ### Maven
          \`\`\`xml
          <dependency>
              <groupId>io.github.cuihairu.redis-streaming</groupId>
              <artifactId>MODULE_NAME</artifactId>
              <version>${version}</version>
          </dependency>
          \`\`\`

          ### Gradle
          \`\`\`gradle
          implementation 'io.github.cuihairu.redis-streaming:MODULE_NAME:${version}'
          \`\`\`
          `;

          github.rest.repos.createReleaseComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: context.payload.release.id,
            body: body
          });

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Publishing to Maven Central failed!"
        echo "Please check the logs for details."
